cat <<EOF | kubectl create -f -
apiVersion: certificates.k8s.io/v1beta1
kind: CertificateSigningRequest
metadata:
  name: test_csr
spec:
  groups:
  - system:authenticated
  request: $(cat test.csr | base64 | tr -d '\n')
  usages:
  - digital signature
  - key encipherment
  - test auth
EOF