apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  namespace: sample
  name: sample-role
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["deployments", "replicasets", "pods"]
  verbs: ["get", "list", "watch", "create", "update", "patch"] # You can also use ["*"]
[root@master dev]# cat devrolebinding.yaml
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: sample-rolebinding
  namespace: sample
subjects:
- kind: User
  name: dev
  apiGroup: ""
roleRef:
  kind: Role
  name: sample-role
  apiGroup: ""
